### ISSUE TITLE
Arduino Micro

### ISSUE THREAD

**Issue by gonzolenfox** [sstaub/EADOG#2]
Hello,
I hope you are actually activ with your account.
I have problems to program your Demo sketch from yout EADOG library to my arduino Micro.
If I want to program it, it get an Error because of the mbed.h, I guess. 
First, do I need the mbed.h?
I dont have it and I dont know, where I can get.
Is it possible to run your library at an Arduino Micro?

It would be be very nice, if you can help me.

Greetings, Stefan

**Comment by sstaub** [comment]
Sorry, that library is for the mbed framework, for Arduino look to [https://www.lcd-module.de/support/application-note/arduino-meets-ea-dog.html](url)

**Comment by gonzolenfox** [comment]
Hallo,
Ich sehe gerade, dass Sie vermutlich deutsch sprechen bzw. einen deutschen Namen haben.
Die von Ihnen vorgeschlagene Library kenne ich, mit der kann ich jedoch den Text nicht invertieren bzw. Habe nichts darüber finden können.
Ich weiß leider nicht, wie ich hier weiter vorgehen kann.
Trotzdem danke für Ihre Rückmeldung.
Liebe Grüße

**Comment by sstaub** [comment]
Die eigentlichen Befehle zur Displaysteuerung dürften die selben sein wie bei der Arduino library. Für das Invertieren muss `write_command(0xA7);` gesendet werden. Eine entsprechende Kommandofunktion sollte vorhanden sein auch wenn diese dann anders heißt. Eine Version für Arduino aus dieser Library zu schreiben ist theoretisch möglich, aber hat doch Hürden da MBED ein reines C++ Framework ist. Einfach mal den Code ansehen.
